server.port=8081
# ตั้งค่าเชื่อมต่อ MySQL (ชี้ไปที่ virtual_bank)
spring.datasource.url=jdbc:mysql://localhost:3306/virtual_bank
spring.datasource.username=root
spring.datasource.password=Pooht@563810
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ให้ระบบสร้างตารางอัตโนมัติ และโชว์คำสั่ง SQL ตอนรัน
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true