spring.datasource.url=jdbc:mysql://mysql-virtual-bank-project-virtual-bank-project.j.aivencloud.com:23729/defaultdb?sslMode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_FiU6LWaeYo885UeSL93
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true